/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id ("com.adarshr.test-logger") version "4.0.0"
    application
    java
}

apply {
    plugin ("com.adarshr.test-logger")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }

application {
    // Define the main class for the application.
    mainClass = "org.auto_backup.App"
}


tasks.register<Copy>("cpResources") {
    // Task info
    group = "Verification"
    description = "Copies test resources"

    // Copy logic
    val dirFrom = "${projectDir}/src/test/resources"
    var dirTo = "${getLayout().getBuildDirectory().get().asFile.absolutePath}/classes/test"
    from (dirFrom)
    into (dirTo)

    // Loging
    doFirst {
        logger.info(dirFrom)
        logger.info(dirTo)
    }
    doLast {
        logger.info("Files copied SUCCESSFULLY")
    }
}
tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    testLogging.showStandardStreams = true
    dependsOn("cpResources")
    useJUnitPlatform()
}

testlogger {
    // theme = ThemeType.MOCHA
    showExceptions = true
    showStackTraces = true
    showFullStackTraces = false
    showCauses = true
    slowThreshold = 2000
    showSummary = true
    showSimpleNames = false
    showPassed = true
    showSkipped = true
    showFailed = true
    showOnlySlow = false
    showStandardStreams = false
    showPassedStandardStreams = true
    showSkippedStandardStreams = true
    showFailedStandardStreams = true
    logLevel = LogLevel.LIFECYCLE
}
